# MySQL database connection
spring.datasource.url=jdbc:mysql://localhost:3306/requestdb?useSSL=false&serverTimezone=UTC
spring.datasource.username=appuser
spring.datasource.password=mahakal@10

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
